In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

x = torch.rand(3, 4, 5).type(torch.float32)

In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
x.view(6, 10)

tensor([[0.4388, 0.3571, 0.4206, 0.0885, 0.3868, 0.6712, 0.6933, 0.8090, 0.7708,
         0.6158],
        [0.5520, 0.0265, 0.0431, 0.4190, 0.1024, 0.9375, 0.7369, 0.2060, 0.8832,
         0.4088],
        [0.9927, 0.1758, 0.4769, 0.9981, 0.2011, 0.7184, 0.8774, 0.3517, 0.5306,
         0.6843],
        [0.9577, 0.6247, 0.2363, 0.0296, 0.4875, 0.4863, 0.6695, 0.8070, 0.3338,
         0.1621],
        [0.5925, 0.9180, 0.7076, 0.8747, 0.4128, 0.0360, 0.6286, 0.1174, 0.8843,
         0.4653],
        [0.2103, 0.0359, 0.5424, 0.5979, 0.8174, 0.1444, 0.0861, 0.6754, 0.4434,
         0.4214]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x * torch.DoubleTensor([1, 4, 2, 2, 1])

tensor([[[0.4388, 1.4283, 0.8411, 0.1770, 0.3868],
         [0.6712, 2.7733, 1.6181, 1.5415, 0.6158],
         [0.5520, 0.1059, 0.0861, 0.8380, 0.1024],
         [0.9375, 2.9476, 0.4120, 1.7664, 0.4088]],

        [[0.9927, 0.7031, 0.9537, 1.9962, 0.2011],
         [0.7184, 3.5095, 0.7035, 1.0612, 0.6843],
         [0.9577, 2.4988, 0.4726, 0.0593, 0.4875],
         [0.4863, 2.6781, 1.6139, 0.6676, 0.1621]],

        [[0.5925, 3.6721, 1.4153, 1.7495, 0.4128],
         [0.0360, 2.5142, 0.2347, 1.7685, 0.4653],
         [0.2103, 0.1438, 1.0849, 1.1957, 0.8174],
         [0.1444, 0.3443, 1.3507, 0.8869, 0.4214]]], dtype=torch.float64)

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.matmul(x.view(6, 10), torch.transpose(x.view(6, 10), 1, 0))

tensor([[3.2134, 2.5858, 3.0704, 2.7344, 2.6455, 2.0065],
        [2.5858, 2.9049, 3.1529, 2.0943, 2.2830, 1.3764],
        [3.0704, 3.1529, 4.4397, 2.8095, 3.4493, 2.1752],
        [2.7344, 2.0943, 2.8095, 3.0755, 2.4390, 1.6573],
        [2.6455, 2.2830, 3.4493, 2.4390, 4.0387, 2.1286],
        [2.0065, 1.3764, 2.1752, 1.6573, 2.1286, 2.2238]])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.FloatTensor([1]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]), requires_grad = True)

y = x**3 + z -75*t

In [8]:
y.backward([x, z, t])

In [9]:
x.grad

tensor([3.])

In [10]:
z.grad

tensor([1.])

In [11]:
t.grad

tensor([-75.])

In [12]:
# Создайте единичный тензор размера 5x6

x = torch.ones((5, 6))

In [13]:
# Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [14]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

from torch import nn

In [15]:
x = torch.FloatTensor([1])
w = Variable(torch.FloatTensor([1]), requires_grad=True)

y = x ** w -2 * x**2 + 5

In [16]:
from torch import nn 
from torch import optim

In [17]:
optimizer = optim.SGD([w], lr=0.01)
criterion = nn.MSELoss()

In [18]:
w = nn.Linear(1, 1, bias=False)

In [27]:
optimizer.zero_grad()
x = torch.FloatTensor([100])
pred = x ** w(torch.FloatTensor([1])) -2 * x**2 + 5
loss = criterion(pred, y)
loss

tensor(3.9970e+08, grad_fn=<MseLossBackward>)

In [25]:
loss.backward()

In [28]:
optimizer.step()

In [29]:
pred

tensor([-19988.4746], grad_fn=<AddBackward0>)

In [30]:
target = torch.FloatTensor([10])
target

tensor([10.])

In [31]:
w.weight.grad

tensor([[-1201648.6250]])

In [32]:
w

Linear(in_features=1, out_features=1, bias=False)